version: "3"

services:
  postgres_elixir:
    image: postgres:12.2
    container_name: postgres_elixir
    volumes:
      - ./postgres-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Cine
    ports:
      - 5432:5432